#!/bin/bash
# Демо: светодиоды + LCD — случайная фраза
# LCD: 16 символов на строку, 2 строки, только ASCII

CDIR="$(cd "$(dirname "$0")" && pwd)"
CTL="$CDIR/../aura-indicator/bin/aura-ctl"
pad() { local s="$1"; printf "%-16s" "${s:0:16}"; }
join() { echo "$(pad "$1")$(pad "$2")"; }

# Пары фраз: строка0 | строка1 (каждая ≤ 16 ASCII символов)
# ~100 штук — IT, кино, игры, мемы, жизнь
phrases=(
  # Tech / Programming (25)
  "Hello world!|It's me, Bob!"
  "sudo make me|a sandwich"
  "It's not a bug|it's a feature"
  "Trust me,|I'm a dev"
  "Coffee: ON|Sleep: OFF"
  "Let's GO!|Debugging..."
  "404|Wisdom absent"
  "Loading...|Please wait"
  "Insert coin|to continue"
  "git commit|-m 'it works'"
  "while(true)|coffee++"
  "It compiles|ship it!"
  "npm install|pray for me"
  "Seg fault|core dumped"
  "In theory,|in practice"
  "chmod 777|fixes all"
  "I'll fix it|tomorrow? ;)"
  "Deploy on|Friday!"
  "Running tests|please wait"
  "Going to prod|hold my beer"
  "Works on my|machine"
  "Refactoring|is refactoring"
  "I need a|vacation..."
  "Final build|v0.0.1-alpha"
  "Deploying...|fingers crossed"

  # Movies / TV (25)
  "May the Force|be with you"
  "To infinity|and beyond!"
  "Hakuna|Matata!"
  "Winter is|coming..."
  "You shall not|pass!"
  "I am Groot|I am Groot"
  "I find your|lack of faith"
  "One does not|simply walk"
  "Run away!|To the hills"
  "Why so|serious?"
  "I'll be back|Terminator"
  "E.T. go home|Phone home."
  "The cake is|a lie."
  "Resistance is|futile."
  "Pizza time!|Mamma mia!"
  "Live long and|prosper."
  "Make it so|Number One"
  "Houston...|we have a prob"
  "Open the pod|bay doors Hal"
  "My precious|Gollum"
  "You're a|wizard, Harry"
  "This is the|way."
  "I have a bad|feeling..."
  "Not the droids|you're looking"
  "Bond. James|Bond."

  # Life / Memes / Misc (50)
  "Keep calm and|carry on."
  "Just do it!|...tomorrow"
  "This is fine|I'm okay"
  "You had ONE|job!"
  "Plot twist:|a feature!"
  "To be or not|to be"
  "I need coffee|and a nap"
  "Monday again|send help"
  "TGIF!|is it Monday?"
  "Almost there|keep going"
  "One more push|you got this"
  "Don't panic|it's fine"
  "Patience is|a virtue"
  "Never give up|never give in"
  "If at first|try again"
  "Practice makes|progress"
  "Eat. Sleep.|Code. Repeat."
  "All your base|are belong to"
  "What's cooking|good looking"
  "The answer is|42"
  "Don't forget|your towel"
  "You just got|pwned."
  "Has anyone|seen my keys?"
  "Where am I|what is this?"
  "Why did I|come in here?"
  "Today is a|good day"
  "Carpe diem|seize the day"
  "You are valid|and capable"
  "Breathe in|breathe out"
  "Take a break|relax..."
  "I'm not lazy|I'm on standby"
  "I'm not arguing|I'm just wrong"
  "Multitasking|badly."
  "Professional|procrastinator"
  "I'd like to|cancel my sub"
  "Go away|I'm sleeping"
  "In desperate|need of tea"
  "Existential|crisis mode"
  "Humans are|weird"
  "How do I|adult today?"
  "No thoughts|head empty"
  "Brain: off|body: auto"
  "I require|more caffeine"
  "Do not|disturb"
  "Genius at|work. shh!"
  "Please stand|by..."
  "All systems|nominal."
  "Happy little|accidents"
  "Live, Laugh,|L33T H4X0R"
  "You had me at|hello world"
)

idx=$(( RANDOM % ${#phrases[@]} ))
IFS='|' read -r line0 line1 <<< "${phrases[$idx]}"

$CTL lcd "$(join "$line0" "$line1")"
$CTL off led2

echo "Done! (phrase #$idx: ${line0} | ${line1})"
