#!/bin/bash
# Демо: светодиоды + LCD — случайная фраза (смешанный рус/англ)
# LCD: 16 символов на строку, 2 строки, UTF-8 кириллица

CDIR="$(cd "$(dirname "$0")" && pwd)"
CTL="$CDIR/../aura-indicator/bin/aura-ctl"
pad() { local s="$1"; printf "%-16s" "${s:0:16}"; }
join() { echo "$(pad "$1")$(pad "$2")"; }

# Пары фраз: строка0 | строка1 (каждая ≤ 16 символов)
# Смешанные русские и английские выражения
phrases=(
  # === IT / Программирование ===
  "Hello world!|Привет мир!"
  "sudo make me|butterface"
  "Это не баг,|это feature"
  "Trust me,|я developer"
  "Kofe: ON|Son: OFF"
  "Let's GO!|Debugging..."
  "404|Um ne nayden"
  "Zagruzka...|Podozhdite"
  "Vstavte monetu|dlya prodolzh"
  "git commit|-m 'rabotaet'"
  "while(true)|kofe++"
  "Kompiliruetsya|otpravlyaj!"
  "Seg fault|core dumped"
  "V teorii,|na practice"
  "chmod 777|reshaet vsyo"
  "Ya ispravlyu|zavtra? ;)"
  "Deploj v|pyatnitsu!"
  "Testy idut|podozhdite"
  "V productiyu|derzhi pivo"
  "Rabotaet na|moem PC"
  "Refactoring|est refactoring"
  "Mne nuzhen|otpusk..."
  "Final build|v0.0.1-alpha"
  "Deploying...|derzhi menya"

  # === Кино / ТВ / Игры ===
  "May the Force|budet s toboy"
  "Do beskonech-|nosti i dal'she!"
  "Hakuna|Matata!"
  "Zima|blizko..."
  "Ty ne proydesh|!"
  "Ya Groot|Ya Groot"
  "Ya vizhu tvo-|yu neveru"
  "Nikto ne|prosto pryg-ni!"
  "Begom!|Na kholmy"
  "Pochemu tak|ser'ezno?"
  "Ya vernus|Terminator"
  "E.T. domoj|Pozvoni domoj"
  "Tort — eto|lozh'!"
  "Soprotivle-|nie bespolezno"
  "Vremya pitstsy|Mamma mia!"
  "Zhivi dolgo|i protsvetaj"
  "Sdelaj tak|Pervyj nomer"
  "Houston...|u nas problema"
  "Otkroy shlyuz|Hal"
  "Moyo drazno-|ye... Gollum"
  "Ty — volsh-|ebnik, Gerri"
  "The way|is this"
  "U menya durn-|oe chuvstvo..."
  "Ne te droidy|kotorye ty ishesh"
  "Bond. Dzhejms|Bond."

  # === Жизнь / Мемы / Смешное ===
  "Soxraj spoko-|jstvie i rabotaj"
  "Prosto sdelaj!|...zavtra"
  "Vse v poryadke|ya v norme"
  "U tebya byla|ODNA zadacha!"
  "Syuzhetnyi|povorot: feature"
  "Byt' ili ne|byt'"
  "Mne nuzhen|kofe i son"
  "Ponedelnik|snova pomogite"
  "Pjatnica!|Uzhe ponedelnik?"
  "Pochti doshli|dержись"
  "Yeshche raz|ty smozhesh"
  "Ne panikuj|vsyo ok"
  "Terpenie —|drug"
  "Nikogda ne|sdavajsya"
  "Esli ne|poluchilos snova!"
  "Praktika|sovershenstvuet"
  "Est. Spat.|Kodit. Povtoryat."
  "Otvet na vsyo|42"
  "Ne zabud|svoj polotence"
  "Segodnya|horoshij den'"
  "Carpe diem|khvatij den'"
  "Ty validen|i sposoben"
  "Vdohni|vыdohni"
  "Otdohni|raslablyajsya"
  "Ya ne leniv|ya v standby"
  "Ya ne sporyu|ya prosto neprav"
  "Multizadach-|nost plokho."
  "Prokrasti-|nator profi"
  "Ya hochu|otmenit' podpis"
  "Uydi|ya spyu"
  "Mne nuzhen|chaj srochno"
  "Eksistenc-|ial'nyj krizis"
  "Lyudi —|strannye"
  "Kak vzros-|lej dumat'?"
  "Net myslej|golova pusta"
  "Mozg: VYL|Telo: AVTO"
  "Mne nuzhen|bol'she kofeina"
  "Ne bespokoit'"
  "Genij|rabotaet. shh!"
  "Podozhdite|..."
  "Vse sistemy|v norme."
  "Schastlivye|melochi"
  "Zhivi, Smeyis|L33T H4X0R"
  "Ty menya|vzyal helloworld"
)

idx=$(( RANDOM % ${#phrases[@]} ))
IFS='|' read -r line0 line1 <<< "${phrases[$idx]}"

$CTL lcd "$(join "$line0" "$line1")"
$CTL off led2

echo "Done! (phrase #$idx: ${line0} | ${line1})"
